export enum ClienteEnum {
  ID = 'id',
  CODIGO = 'codigo',
  PRIMEIRO_NOME = 'primeiro nome',
  SOBRENOME = 'sobrenome',
  TIPO_CADASTRO = 'tipo cadastro',
  DATA_NASCIMENTO = 'data de nascimento',
  RG = 'rg',
  CPF_CNPJ = 'cpf/Cnpj',
  CEP = 'cep',
  LAGRADOURO = 'lagradouro',
  NUMERO = 'número',
  BAIRRO = 'bairro',
  COMPLEMENTO = 'complemento',
  CIDADE = 'cidade',
  ESTADO = 'estado',
  ENDERECO_CORRESPONDENCIA = 'endereço de correspondência',
  CELULAR = 'celular',
  CELULAR_ALTERNATIVO = 'celular alternativo',
  TELEFONE_RESIDENCIAL = 'telefone recidênciaL',
  TELEFONE_COMERCIAL = 'telefone comercial',
  PERMITE_SMS = 'permite envio de sms',
  EMAIL = 'email',
  EMAIL_ALTERNATIVO = 'email alternativo',
  PLANO = 'plano',
  AUTORIZA_NFE = 'autoriza envio de nfe',
  FOMRA_ENVIO_EXTRATO = 'forma de envio de extrato',
}
